//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acreedor
    {
        public Acreedor()
        {
            this.Paquete = new HashSet<Paquete>();
        }
    
        public string ClaveAcre { get; set; }
        public string DescripcionAcre { get; set; }
    
        public virtual ICollection<Paquete> Paquete { get; set; }
    }
}
