//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        public Paquete()
        {
            this.Reembolso = new HashSet<Reembolso>();
        }
    
        public int FolioPaq { get; set; }
        public string ClaveAcre { get; set; }
        public decimal ImportePaq { get; set; }
        public System.DateTime CreacionPaq { get; set; }
        public int ID_StatusPaq { get; set; }
        public System.DateTime CierrePaq { get; set; }
        public int ID_Usuario { get; set; }
        public decimal PresupuestoPaq { get; set; }
    
        public virtual Acreedor Acreedor { get; set; }
        public virtual StatusPaq StatusPaq { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Reembolso> Reembolso { get; set; }
    }
}
