//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reembolso
    {
        public int ID_Reem { get; set; }
        public int FolioPaq { get; set; }
        public string ClaveArt { get; set; }
        public string ClaveProv { get; set; }
        public string DescripcionReem { get; set; }
        public decimal ImporteRem { get; set; }
        public int IVA_Reem { get; set; }
        public decimal TotalReem { get; set; }
        public System.DateTime FechaReem { get; set; }
        public string ClaveSuc { get; set; }
        public string ClaveSeg { get; set; }
        public System.DateTime CreacionReem { get; set; }
        public int ID_Usuario { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Paquete Paquete { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Segmento Segmento { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
