//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Paquete = new HashSet<Paquete>();
            this.Reembolso = new HashSet<Reembolso>();
            this.Usuario_Modulo = new HashSet<Usuario_Modulo>();
        }
    
        public int ID_Usuario { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Rol { get; set; }
    
        public virtual ICollection<Paquete> Paquete { get; set; }
        public virtual ICollection<Reembolso> Reembolso { get; set; }
        public virtual Rol Rol1 { get; set; }
        public virtual ICollection<Usuario_Modulo> Usuario_Modulo { get; set; }
    }
}
