//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Modulo
    {
        public int ClaveUM { get; set; }
        public int ID_Usuario { get; set; }
        public int ClaveMod { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
